<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>true</IsPackable>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageId>Brazilian.PrimitivesTypes.EntityFrameworkCore.SqlServer</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>nuget-icon.png</PackageIcon>
    <Description>Entity Framework Core SQL Server integration for Brazilian.PrimitivesTypes value objects.</Description>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RootNamespace>Brazilian.PrimitivesTypes.EntityFrameworkCore.SqlServer</RootNamespace>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Brazilian.PrimitivesTypes/Brazilian.PrimitivesTypes.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../README.pt-BR.md" Pack="true" PackagePath="/" />
    <None Include="../../README.en.md" Pack="true" PackagePath="/" />
    <None Include="resource/nuget-icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
